-- schema_migration.sql
-- Schema Migration Script

-- Oracle Database Scripts
-- Author: Jean Alves
-- Position: Systems Analyst | Software Engineer | Oracle Database Specialist

-- Step 1: Create New Tables (if applicable)
CREATE TABLE customers_new (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    phone_number VARCHAR2(15),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Step 2: Migrate Data from Old Table
INSERT INTO customers_new (customer_id, name, email, created_at)
SELECT customer_id, name, email, created_at FROM customers;

-- Step 3: Rename Old Table (Backup)
ALTER TABLE customers RENAME TO customers_old;

-- Step 4: Rename New Table to Original Name
ALTER TABLE customers_new RENAME TO customers;

-- Step 5: Drop Old Table (if necessary, after verification)
-- DROP TABLE customers_old;

-- Step 6: Update Constraints or Indexes (if needed)
CREATE INDEX idx_customer_email ON customers(email);